---
language: node_js
node_js:
  - "node"

sudo: required 

cache:
  directories:
    - $HOME/.npm

dist: trusty

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.18.2
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true

before_install:
  - npm config set spin false
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - npm test

addons:
  chrome: stable
