---
language: node_js
node_js:
  - "6"

sudo: required 

cache:
  directories:
    - $HOME/.npm

dist: trusty

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.18.2
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true

before_install:
  - npm config set spin false

install:
  - npm install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - npm test
  - npm run coverage

after_success:
  - npm run coveralls

addons:
  chrome: stable
