name: CI

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v1
    - uses: rwjblue/setup-volta@v1
    - name: Install
      run: yarn install --frozen-lockfile
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
    - name: ESLint
      run: yarn lint:js
    - name: Templates
      run: yarn lint:hbs
    - name: Test ember compatibility
      run: yarn test:ember-compatibility 
    - name: Build
      run: |
            yarn ember build --environment=production
            cp dist/index.html dist/404.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

    - name: Release
      env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn semantic-release

